"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }}>
          <Sidebar />
          <Box sx={{ ml: { md: "260px", xs: "65px" }, flex: 1 }}>
            <Navbar />
          </Box>
        </Box>
        <Box sx={{ ml: { md: "260px", xs: "65px" } }}>{children}</Box>
      </body>
    </html>
  );
}
